# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38904f03d8b9f1f785cdff090319aeb1ea1b79529508cc222781013626fc84dea4aba2da99a7725e93a4e37605c9911fd721c95f650ef9f89ad4fbeba56c84d4

test:
  secret_key_base: 75da91c19bd56383de75b61d80be4735ff5d1777942a32e8f5d5248ea14a40449b2cee8b26a2ac6bbb9ae51df18c9a6cb2ff34a8d35a11bcccf58b8453e272fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
